pipeline {
    agent { docker 'quay.io/sudipt/terra_python' } 
    stages {
        stage('Checkout SCM') {
            steps {
				checkout([$class: 'GitSCM', branches: [[name: '*/feature']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitLabCredens', url: 'https://gitlab.com/ot-aws/terrafrom_v0.12.21/network_skeleton.git']]])
            }
        }
        stage('Backend Bucket Creation'){
            steps {
                sh "cd examples && python3 pre_init.py"
            }
        }
        stage('Terraform init'){
            steps {
                dir('examples') {
                    sh "terraform init"
                }
            }
        }
        stage('Terraform plan'){
            steps {
                dir('examples') {
                    sh "terraform plan "
                }
            }
        }
        stage('Terraform apply'){
            steps {
                dir('examples') {
                    sh "terraform apply -auto-approve"
                }
            }
        }
        stage('Slack Notify'){
            steps {
                slackSend channel: 'ot-aws', message: 'Terraformed well!!'
            }
        }		
    }
}
